language: python

python:
- '3.5'

install: make install

script: make test

deploy:
  provider: pypi
  user: datacamp
  password:
    secure: e22oN9tU0SbVN678QadHprErnnpCrLR5SaX/Yq8ZXjgA2f2+8yLFB7xi+FWNEL2wsRjAD4R1drmX4J65EQ1jFgA2dFEDKnhGjtyC5z+Rz7LEL509zwrzVXhavEZVPwASZG3xKX1qW6p3xSerdJaoH0zci8mGcmvbfAOPPIIgK8K0lTCV9Ueqdj1MkWRmfj1xfai+9vv54S+6ZgiJYJJleKgtAohyO1RPczuQqkSPHIzeYHMaHgAiVBNmBKMRTxtMVBTsh8i8fhLsI3RnjoWjt7tHwt+K1grlIMiYKQujwqC6bipYBkz+deD56Qde4GZBrOqCz3f/rzqhDmxH8kC2Zo0vktUqzVs0wJUzLJV1CYquCo3sARAm/iYtMI0c0AhXE5JEJDliRRqsp/2RSLazmYNKLcsH0urV+jkM8xqol/Yn82LAXW4RWHet0+s+n9QkDizzFtDX9sSMzVwFvkcBmYipimfb3FzcV52/STCkJ2BP50cn+en4AsXK7EfgxKc31BbXGXJAJq9m/CZ2OCJEJGJsckZAP8UQyNdVehanQFc6wUH2aFF9bV89aJu0Z6fYugcWFZN8DgfblnULd+cGEVmt2u4KNG30VivtYnG1mzkgD+sog0U6o57HFWDcUuiwrtRrAbbgJjjCQgRVCnLSToKBvvF7B4wxXW38tmPEJKc=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datacamp/shellwhat_ext
    skip_upload_docs: true
